language: ruby
cache: bundler

rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - ruby-head

before_install:
  - gem update bundler

script: bundle exec rake spec

notifications:
  irc: "irc.freenode.org#tdiary"

matrix:
  allow_failures:
    - rvm: ruby-head
